Traceback (most recent call last):
  File "C:\Users\gabri\miniconda3\envs\programacioi\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\gabri\miniconda3\envs\programacioi\Lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gabri\miniconda3\envs\programacioi\Lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gabri\miniconda3\envs\programacioi\Lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gabri\miniconda3\envs\programacioi\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\gabri\miniconda3\envs\programacioi\Lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\gabri\miniconda3\envs\programacioi\Lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\gabri\miniconda3\envs\programacioi\Lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Darrer cas, intentam eliminar un element que no existeix
c = [1, 2, 3, 4, 5]
c.remove('a')
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mValueError[0m                                Traceback (most recent call last)
Cell [1;32mIn[13], line 3[0m
[0;32m      1[0m [38;5;66;03m# Darrer cas, intentam eliminar un element que no existeix[39;00m
[0;32m      2[0m c [38;5;241m=[39m [[38;5;241m1[39m, [38;5;241m2[39m, [38;5;241m3[39m, [38;5;241m4[39m, [38;5;241m5[39m]
[1;32m----> 3[0m c[38;5;241m.[39mremove([38;5;124m'[39m[38;5;124ma[39m[38;5;124m'[39m)

[1;31mValueError[0m: list.remove(x): x not in list
ValueError: list.remove(x): x not in list

