Traceback (most recent call last):
  File "c:\users\gabri\anaconda3\envs\book\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\gabri\anaconda3\envs\book\lib\site-packages\nbclient\client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\gabri\anaconda3\envs\book\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\gabri\anaconda3\envs\book\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\gabri\anaconda3\envs\book\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\gabri\anaconda3\envs\book\lib\site-packages\nbclient\client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\gabri\anaconda3\envs\book\lib\site-packages\nbclient\client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\gabri\anaconda3\envs\book\lib\site-packages\nbclient\client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Creaci√≥ d'una tupla i us amb funcions
vocals = ('a', 'e', 'i', 'o', 'u')

# Operadors
hi_es = 'u' in vocals

print(hi_es)


long = len(vocals)
print(long)

maxim = max(vocals)
print(maxim)


# Indexacio
vocals[0] = 'A'
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mTypeError[0m                                 Traceback (most recent call last)
[1;32m<ipython-input-1-dca291cfefb3>[0m in [0;36m<module>[1;34m[0m
[0;32m     16[0m [1;33m[0m[0m
[0;32m     17[0m [1;31m# Indexacio[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 18[1;33m [0mvocals[0m[1;33m[[0m[1;36m0[0m[1;33m][0m [1;33m=[0m [1;34m'A'[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;31mTypeError[0m: 'tuple' object does not support item assignment
TypeError: 'tuple' object does not support item assignment

